In [5]:
import time
import numpy as np

In [6]:
x = np.random.random(100000000)

In [8]:
start = time.time()
sum(x / len(x))
print(time.time() - start)

23.993213415145874


In [9]:
start = time.time()
np.mean(x)
print(time.time() - start)

0.2821636199951172


In [10]:
x = np.array([1,2,3,4,5])

In [11]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
x.dtype

dtype('int32')

In [13]:
x.shape

(5,)

In [14]:
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
y.shape

(4, 3)

In [16]:
y.size

12

In [19]:
x = np.array(['Hello', 'World'])
print(x)
print(x.shape)
print(type(x))
print(x.dtype)

['Hello' 'World']
(2,)
<class 'numpy.ndarray'>
<U5


In [21]:
x = np.array([1,2,'World'])
print(x)
print(x.shape)
print(type(x))
print(x.dtype)

['1' '2' 'World']
(3,)
<class 'numpy.ndarray'>
<U11


In [22]:
x = np.array([1, 2.5, 5])
print(x)
print(x.dtype)

[1.  2.5 5. ]
float64


In [27]:
x = np.array([1.5, 2.2, 3.7], dtype=np.int64)
print(x)
print(x.dtype)

[1 2 3]
int64


In [28]:
# saving an array to current directory with filename as my_array
x = np.array([1, 2, 3, 4, 5])
np.save('my_array', x)

In [29]:
# loading array from file into another variable
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]
