In [1]:
import numpy as np

def softmax(L):
    expL = np.exp(L)
    sumExpL = sum(expL)
    result = []
    for i in expL:
        result.append(i*1.0/sumExpL)
    return result
    
    # Note: The function np.divide can also be used here, as follows:
    # def softmax(L):
    #     expL = np.exp(L)
    #     return np.divide (expL, expL.sum())


In [2]:
softmax([5,6,7])

[0.09003057317038046, 0.24472847105479764, 0.6652409557748219]

In [9]:
0.6*0.2*0.1*0.7

0.0084

In [10]:
0.7*0.9*0.8*0.6

0.3024

In [14]:
np.exp(0.6) + np.exp(0.2) + np.exp(0.1) + np.exp(0.7)

6.1624451840968035

In [15]:
np.exp(0.7) + np.exp(0.9) + np.exp(0.8) + np.exp(0.6)

8.521015547510403

In [16]:
np.log10(0.6) + np.log10(0.2) + np.log10(0.1) + np.log10(0.7)

-2.0757207139381184

In [17]:
np.log10(0.7) + np.log10(0.9) + np.log10(0.8) + np.log10(0.6)

-0.5194182131708311

In [18]:
np.sin(0.6) + np.sin(0.2) + np.sin(0.1) + np.sin(0.7)

1.5073629080746158

In [19]:
np.sin(0.7) + np.sin(0.9) + np.sin(0.8) + np.sin(0.6)

2.7095431611597323

In [24]:
np.log(0.6 * 0.2)

-2.120263536200091

In [23]:
np.log(0.6) + np.log(0.2)

-2.120263536200091

In [28]:
y = [1,2,5]
p = [3,4,6]
a1 = np.array(y)
a2 = np.array(p)
a1*a2

array([ 3,  8, 30])

In [29]:
sum(a1 * a2)

41

In [30]:
Y=[1,0,1,1]
P=[0.4,0.6,0.1,0.5]
a1 = np.array(Y)
a2 = np.array(P)
print(a2)
log_a2 = np.log(a2)
print(log_a2)

[0.4 0.6 0.1 0.5]
[-0.91629073 -0.51082562 -2.30258509 -0.69314718]


In [31]:
Y*log_a2

array([-0.91629073, -0.        , -2.30258509, -0.69314718])

In [34]:
sum(Y*log_a2) *-1

3.912023005428146

In [33]:
y1 = 1-a1
y1

array([0, 1, 0, 0])

In [35]:
# Cross Entropy 2
import numpy as np

def cross_entropy(Y, P):
    Y = np.float_(Y)
    P = np.float_(P)
    return -np.sum(Y * np.log(P) + (1 - Y) * np.log(1 - P))

cross_entropy([1,0,1,1], [0.4,0.6,0.1,0.5])

4.828313737302301